{% set version = "1.1.1" %}

package:
  name: qwtpolar
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/qwtpolar/files/qwtpolar/{{ version }}/qwtpolar-{{ version }}.tar.bz2
  sha256: 6168baa9dbc8d527ae1ebf2631313291a1d545da268a05f4caa52ceadbe8b295
  patches:
    # Allow relocatable install
    - qwtpolarconfig.pri.patch
    # don't build debug on Windows - fails as Qwt isn't debug
    - config.patch  # [win]
    # add the _conda suffix patch
    - conda_suffix.patch  # [win]

build:
  number: 7
  skip: true  # [win and vc<14]
  merge_build_host: true  # [linux]
  run_exports:
    - {{ pin_subpackage('qwtpolar', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
  host:
    - qt
    - qwt

test:
  commands:
    - test -f ${PREFIX}/lib/libqwtpolar${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qwtpolar_conda.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qwtpolar_conda.lib exit 1  # [win]

about:
  home: http://qwtpolar.sourceforge.net/
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Polar coordinate system plots for Qwt

extra:
  recipe-maintainers:
    - ceholden
