{% set version = "1.1.1" %}

package:
  name: qwtpolar
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/qwtpolar/files/qwtpolar/{{ version }}/qwtpolar-{{ version }}.tar.bz2
  sha256: 6168baa9dbc8d527ae1ebf2631313291a1d545da268a05f4caa52ceadbe8b295
  patches:
    # Allow relocatable install
    - qwtpolarconfig.pri.patch
    # don't build debug on Windows - fails as Qwt isn't debug
    - config.patch  # [win]

build:
  number: 6
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext-devel') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libXau') }}  # [linux]
  host:
    - qt
    - qwt
  run:
    - qt
    - qwt

test:
  commands:
    - test -f ${PREFIX}/lib/libqwtpolar${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\qwtpolar.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qwtpolar.lib exit 1  # [win]

about:
  home: http://qwtpolar.sourceforge.net/
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Polar coordinate system plots for Qwt

extra:
  recipe-maintainers:
    - ceholden
