{% set version = "1.1.1" %}

package:
  name: qwtpolar
  version: {{ version }}

source:
  fn: qwtpolar-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/qwtpolar/files/qwtpolar/{{ version }}/qwtpolar-{{ version }}.tar.bz2
  md5: 0f549b51a06fa0f0f43b12f3269fe206
  patches:
    # Allow relocatable install
    - qwtpolarconfig.pri.patch

build:
  number: 3

requirements:
  build:
    - qt 5.6.*
    - qwt 
  run:
    - qt 5.6.*
    - qwt

test:
  commands:
    - test -f ${PREFIX}/lib/libqwtpolar.so  # [linux]
    - test -f ${PREFIX}/lib/libqwtpolar.dylib  # [osx]

about:
  home: http://qwtpolar.sourceforge.net/ 
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Polar coordinate system plots for Qwt

extra:
  recipe-maintainers:
    - ceholden
