{% set version = "1.1.1" %}

package:
  name: qwtpolar
  version: {{ version }}

source:
  fn: qwtpolar-{{ version }}.tar.bz2
  url: https://sourceforge.net/projects/qwtpolar/files/qwtpolar/{{ version }}/qwtpolar-{{ version }}.tar.bz2
  md5: 0f549b51a06fa0f0f43b12f3269fe206
  patches:
    # Allow relocatable install
    - qwtpolarconfig.pri.patch
    # don't build debug on Windows - fails as Qwt isn't debug
    - config.patch  # [win]

build:
  number: 4
  skip: True  # [win and py36]
  features:
    - vc9     # [win and py27]
    - vc10    # [win and py34]
    - vc14    # [win and py>=35]
    
requirements:
  build:
    - python  # [win]
    - qt 5.6.*
    - qwt 
    - toolchain
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]
  run:
    - qt 5.6.*
    - qwt
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]

test:
  commands:
    - test -f ${PREFIX}/lib/libqwtpolar.so  # [linux]
    - test -f ${PREFIX}/lib/libqwtpolar.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\\qwtpolar.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\qwtpolar.lib exit 1  # [win]

about:
  home: http://qwtpolar.sourceforge.net/ 
  license: Qwt, Version 1.0
  license_file: COPYING
  summary: Polar coordinate system plots for Qwt

extra:
  recipe-maintainers:
    - ceholden
