appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gH2R7gsuSshiNFetVxmFH0snjDiky+sbTs5InNFUjGV7k5PKk/rZh7BI2/H4v2wyW8+wOMnAGEd2UV0gnVQJMpZm3Jd0yDEhRQ5IQRgyeSPtqUeVT2drFSiz4UOvvRrP7ZJuvnKPP4i7flryScXGa73zXwkJeQAmPVyYB/pT3AT1+83fbZWfKLWsGetTeGz/uKq+XU4v6i/uq/dgSuti4zAYwv4tI7QVjcDKvkLVKShES22WVq4D3dxgTN4IMuAcNOtr1rmqdHSpeIZ6zR3TUpm0PGycOuMIRtdJLvbTSmEZ17tj6PLytXvqvhI/LiP/sYe6nhfZQJ9Fawv96b/TJz6mKCpInPfV13SaVuxhPej/Q2yFROIPth8IqzLFq3aVDVpr+a2wiZWzl2xFobYWxggqzEZ4HXC8VTSTCGXuD9XOMvPze1zNUXrcNRiedZuLWQ/zr2jMsQBmO2Db09on843ArV1OJtxBuluQd9wWAsw9YDioDncb3fNJCnngFuMY2MJ98iOswjsQA85HX9rE3bh9P0yzQv8KuLSDjTuL0SJpHHQnD4PAkyxhgn+biuoiXGIUrIN+WOq6H2IchmvuWejvN3au/8i3yIwhKY+/3jgXgVAdwCBoRwxJYYAsS/mh4VZeOmn8mtQ9EMkmw8yzJqjwJjVEaOF241sFCaCKxqw=}
