travis:
  secure:
    BINSTAR_TOKEN: fwgstWrI3wrWK+2ieIF9BOn+apo7s7TaaBRS2H8Gy6FX9JejU2gOJj92WNIGgMY4Nh+r99QU2Z9NdcBbvxd9JXwT/SpIyStOMYagt16haP9Skg0qq/pwENICHqHxa44DNjleVvHta1N7KVexNQZBU6Mx7V+hY1qXlRwYAeM+I5Lxzizvd0MaVvTE1EB9HElW7VsM7A7LHjxIpxDyXA559yzLqXkKX+FTwM72CyeARjNpUlgEbusIdHSZgqW/jrv2T4nnRgMxBb/G1MaCJykiEWN/Ga3EPRla5jhQbWnAMndi6PBn641FDweA6GsCgirq5hOZ6ZP4zmUKIs2c2NmM+LvSs5YA/nnAaeLZB8J20OguH1oZvLQSwtvr0oDBraWvS3V7uM4QFiqs9TXDiTgv/uO+CfA848Vkpv2UHQxFKTVH9VNva+4/EifyveKqtkwUYbJQhz5FNLiJQR0FDWfJ4dXd9r6Lh3YomuoDndUtrWVvD42mbZIH3s1DUqGejWY+djtYQuTmrgZXfEucPyNIi/oPm3HhQ2vf2GdFhMlPZ/2sm1nT9TSMLegQg4iVz52FVPu2U9I8NAgRtkw97oydugk9/b+VjtVrE41pvSBI9MbSpDyALYD0dG0C4GmB5zwohiTthggwOzruXWRl5W+d4N/Aza2CMTwYeCdpryLZDZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
